- hosts: localhost
  connection: local
  tasks:
    - name: Install and configure tlp
      block:
        - name: Install tlp
          dnf:
            state: present
            name:
              - tlp
              - tlp-rdw

        - name: Add tlp config file
          copy:
            src: "{{ playbook_dir }}/dotfiles/etc/tlp.conf"
            dest: "/etc/tlp.conf"
            remote_src: true
      become: true
      become_user: root
      tags: installtlp

    - name: Configure pulseaudio
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - {
            src: "{{ playbook_dir }}/dotfiles/etc/pulse/daemon.conf",
            dest: "/etc/pulse/daemon.conf",
          }
        - {
            src: "{{ playbook_dir }}/dotfiles/etc/pulse/default.pa",
            dest: "/etc/pulse/default.pa",
          }
      become: true
      become_user: root
      tags: confpulseaudio

    - name: Install Brave Browser
      block:
        - name: Install dnf-plugins-core
          dnf:
            state: present
            name: dnf-plugins-core

        - name: Add Brave's repo
          command:
            cmd: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
            warn: false

        - name: Import Brave's asc
          command:
            cmd: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
            warn: false

        - name: Install Brave
          dnf:
            state: present
            name: brave-browser
      become: true
      become_user: root
      tags: installbrave

    - name: Install and configure VSCode
      block:
        - name: Import Microsoft's asc
          command:
            cmd: rpm --import https://packages.microsoft.com/keys/microsoft.asc
            warn: false

        - name: Add VSCode's repo content
          shell: 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" 
                  > /etc/yum.repos.d/vscode.repo'

        - name: Install VSCode
          dnf:
            state: present
            name: code

        - name: Import VSCode's settings
          copy:
            src: "{{ playbook_dir }}/dotfiles/.config/Code/"
            dest: "{{ lookup('env', 'HOME') }}/.config/Code"
            remote_src: true
          become: false  
      become: true
      become_user: root
      tags: installvscode

    - name: Install Gnome-tweaks
      dnf:
        state: present
        name: gnome-tweak-tool
      become: true
      become_user: root
      tags: installgnometweaks

    - name: Install Gnome Extensions
      include_role: 
        name: jaredhocutt.gnome_extensions
      vars:
        gnome_extension_ids:
          - 615
          - 1485
      tags: installgnomeextensions

    - name: Install and configure zsh and powerlevel10k
      block:
        - name: Install util-linux-user
          dnf:
            state: present
            name: util-linux-user
          become: true
          become_user: root

        - name: Install zsh
          dnf:
            state: present
            name: zsh
          become: true
          become_user: root

        - name: Get zsh path
          command: which zsh
          register: zsh_path

        - name: Change default shell
          command: chsh -s {{ zsh_path.stdout }} {{ lookup('env', 'USER') }}
          become: true
          become_user: root

        - name: Download and install powerlevel10k
          git:
            repo: https://github.com/romkatv/powerlevel10k.git
            dest: "{{ lookup('env', 'HOME') }}/.powerlevel10k"
            depth: 1

        - name: Copy .zshrc config file
          copy:
            src: "{{ playbook_dir }}/dotfiles/.zshrc"
            dest: "{{ lookup('env', 'HOME') }}/.zshrc"
            remote_src: true

        - name: Copy .p10k config file
          copy:
            src: "{{ playbook_dir }}/dotfiles/.p10k.zsh"
            dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
            remote_src: true
      tags: installzsh

    - name: Install and configure Terminator
      block:
        - name: Install Terminator
          dnf:
            state: present
            name: terminator
          become: true
          become_user: root

        - name: Install Meslo fonts
          get_url:
            url: "{{ item }}"
            dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
          loop:
            - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
            - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
            - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
            - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
          become: false
            
        - name: Copy Terminator config folder
          copy:
            src: "{{ playbook_dir }}/dotfiles/.config/terminator/"
            dest: "{{ lookup('env', 'HOME') }}/.config/terminator"
            remote_src: true
      tags: installterminator
    
    - name: Load nano config
      copy:
         src: "{{ playbook_dir }}/dotfiles/.nanorc"
         dest: "{{ lookup('env', 'HOME') }}/.nanorc"
         remote_src: true
      tags: loadnanoconfig

    - name: Load whole dconf
      shell: dconf load / < "{{ playbook_dir }}/dotfiles/dconf-settings.dconf"
      tags: loaddconf

    - name: Debloat GNOME
      dnf:
        name:
          - cheese
          - rhythmbox
          - totem
          - gnome-photos
          - gnome-boxes
          - gnome-maps
          - gnome-contacts
          - gnome-weather
          - gnome-software
        state: absent
        autoremove: yes
      become: true
      become_user: root
      tags: debloatgnome
