- hosts: localhost
  connection: local
  tasks:
    - name: Install and configure tlp
      block:
        - name: Install tlp
          apt:
            state: present
            name:
              - tlp
              - tlp-rdw

        - name: Add tlp config file
          copy:
            src: "{{ playbook_dir }}/dotfiles/etc/tlp.conf"
            dest: "/etc/tlp.conf"
            remote_src: true
      become: true
      become_user: root
      tags: installtlp

    - name: Configure pulseaudio
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - {
            src: "{{ playbook_dir }}/dotfiles/etc/pulse/daemon.conf",
            dest: "/etc/pulse/daemon.conf",
          }
        - {
            src: "{{ playbook_dir }}/dotfiles/etc/pulse/default.pa",
            dest: "/etc/pulse/default.pa",
          }
      become: true
      become_user: root
      tags: confpulseaudio

    - name: Install Brave Browser
      block:
        - name: Install apt-transport-https
          apt:
            state: present
            name: apt-transport-https

        - name: Add Brave's gpg
          command:
            cmd: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
            warn: false

        - name: Import Brave's repo
          copy:
            content: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
            dest: "/etc/apt/sources.list.d/brave-browser-release.list"
            remote_src: true

        - name: Install Brave
          apt:
            state: present
            name: brave-browser
            update_cache: yes
      become: true
      become_user: root
      tags: installbrave

    - name: Install VSCode
      block:
        - name: Install VSCode
          apt:
            deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

      become: true
      become_user: root
      tags: installvscode

    - name: Install and configure zsh and powerlevel10k
      block:          
        - name: Install zsh
          apt:
            state: present
            name: zsh
          become: true
          become_user: root

        - name: Get zsh path
          command: which zsh
          register: zsh_path

        - name: Change default shell
          command: chsh -s {{ zsh_path.stdout }} {{ lookup('env', 'USER') }}
          become: true
          become_user: root

        - name: Download and install powerlevel10k
          git:
            repo: https://github.com/romkatv/powerlevel10k.git
            dest: "{{ lookup('env', 'HOME') }}/.powerlevel10k"
            depth: 1

        - name: Copy .zshrc config file
          copy:
            src: "{{ playbook_dir }}/dotfiles/.zshrc"
            dest: "{{ lookup('env', 'HOME') }}/.zshrc"
            remote_src: true

        - name: Copy .p10k config file
          copy:
            src: "{{ playbook_dir }}/dotfiles/.p10k.zsh"
            dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
            remote_src: true
      tags: installzsh
    
    - name: Load nano config
      copy:
         src: "{{ playbook_dir }}/dotfiles/.nanorc"
         dest: "{{ lookup('env', 'HOME') }}/.nanorc"
         remote_src: true
      tags: loadnanoconfig

    - name: Debloat KDE
      apt:
        name:
          - "akonadi-*"
        state: absent
        autoremove: yes
      become: true
      become_user: root
      tags: debloatkde
      
    - name: Load whole config
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
            - { src: "{{ playbook_dir }}/dotfiles/.config/", dest: "{{ lookup('env', 'HOME') }}/.config" }
            - { src: "{{ playbook_dir }}/dotfiles/.kde/", dest: "{{ lookup('env', 'HOME') }}/.kde" }
            - { src: "{{ playbook_dir }}/dotfiles/.local/", dest: "{{ lookup('env', 'HOME') }}/.local" }
      become: false
      tags: loadconfig
